import React from 'react';
import { Link } from 'react-router-dom';
import CodeBlock from '../../components/CodeBlock';

const AutoRegistration = () => {
    const basicUsageCode = `using MediatRR.ServiceGenerator;

var builder = WebApplication.CreateBuilder(args);

// Auto-register all request handlers in the assembly
builder.Services.AutoRegisterRequestHandlers();

// Auto-register all stream handlers in the assembly
builder.Services.AutoRegisterStreamHandlers();

var app = builder.Build();`;

    const handlerCode = `// Just implement IRequestHandler - no manual registration needed!
namespace MyApp;

public class GetUserQuery : IRequest<User>
{
    public string UserId { get; set; }
}

public class GetUserQueryHandler : IRequestHandler<GetUserQuery, User>
{
    public Task<User> Handle(GetUserQuery request, CancellationToken cancellationToken)
    {
        // Handler implementation
        return Task.FromResult(new User { Id = request.UserId });
    }
}`;

    const generatedCode = `// <auto-generated/>
namespace MediatRR.ServiceGenerator
{
    internal static class SourceGeneratorInjectDependencies
    {
        internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AutoRegisterRequestHandlers(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<global::MediatRR.Contract.Messaging.IRequestHandler<global::MyApp.GetUserQuery, global::MyApp.User>, global::MyApp.GetUserQueryHandler>(services);
            return services;
        }

        internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AutoRegisterStreamHandlers(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            return services;
        }
    }
}`;

    return (
        <div>
            <h1>Auto-Registration</h1>
            <p>
                MediatRR includes a source generator that automatically discovers and registers all
                request and stream handlers in your assembly. This eliminates the need for manual registration
                and reduces boilerplate code.
            </p>

            <h2>How It Works</h2>
            <p>
                The source generator scans your code at compile time, finds the classes that
                implement <code>IRequestHandler&lt;TRequest, TResponse&gt;</code> or{' '}
                <code>IStreamRequestHandler&lt;TRequest, TResponse&gt;</code>, and generates registration code
                automatically. It registers:
            </p>
            <ul style={{ color: 'var(--text-secondary)', marginLeft: '2rem' }}>
                <li>Non-abstract, non-generic classes and records</li>
                <li>Every handler interface a class implements, so one class can handle several request types</li>
                <li>Nested classes, as long as the class and every class it is nested in are public or internal</li>
            </ul>
            <p>
                Notification handlers are not auto-registered; register them
                with <Link to="/docs/notifications">AddNotificationHandler</Link>, which also carries their
                retry policy.
            </p>

            <h2>Usage</h2>
            <p>
                Simply call <code>AutoRegisterRequestHandlers()</code> or <code>AutoRegisterStreamHandlers()</code> on your service collection:
            </p>
            <CodeBlock code={basicUsageCode} />

            <h2>Creating Handlers</h2>
            <p>
                Just implement <code>IRequestHandler</code> - no attributes or manual registration required:
            </p>
            <CodeBlock code={handlerCode} />

            <h2>Generated Code</h2>
            <p>
                Behind the scenes, the source generator creates extension methods that register all handlers.
                Both methods always exist, even when there is nothing to register:
            </p>
            <CodeBlock code={generatedCode} />

            <h2>Requirements</h2>
            <ul style={{ color: 'var(--text-secondary)', marginLeft: '2rem' }}>
                <li>The generator ships inside the MediatRR package; there is nothing else to install</li>
                <li>It runs on the .NET SDK 6.0.400 or later, or Visual Studio 2022 17.3 or later</li>
                <li>
                    The generated code uses only C# 7.3 syntax and fully qualified names, so it also compiles
                    in projects on older language versions, such as <code>netstandard2.0</code> and .NET
                    Framework libraries
                </li>
            </ul>

            <h2>Benefits</h2>
            <ul style={{ color: 'var(--text-secondary)', marginLeft: '2rem' }}>
                <li><strong>Zero Boilerplate</strong>: No need to manually register each handler</li>
                <li><strong>Compile-Time Safety</strong>: Registration happens at compile time, not runtime</li>
                <li><strong>No Reflection</strong>: No assembly scanning at startup - faster application startup</li>
                <li><strong>Automatic Discovery</strong>: New handlers are automatically registered when you add them</li>
                <li><strong>Type Safe</strong>: All registrations are strongly typed</li>
            </ul>

            <h2>Namespace</h2>
            <p>
                The auto-registration feature is available in the <code>MediatRR.ServiceGenerator</code> namespace:
            </p>
            <CodeBlock code="using MediatRR.ServiceGenerator;" language="csharp" />

            <div className="card" style={{ marginTop: '2rem', background: 'rgba(16, 185, 129, 0.1)', borderColor: '#10b981' }}>
                <h3>⚡ Performance Tip</h3>
                <p style={{ marginBottom: 0 }}>
                    Source generators run at compile time, so there's zero runtime overhead. This makes
                    auto-registration faster than traditional assembly scanning approaches used by other
                    mediator libraries.
                </p>
            </div>

            <h2>Combining with Manual Registration</h2>
            <p>
                You can still manually register handlers if needed. A manual registration made after the
                auto-registration call overrides the auto-registered handler:
            </p>
            <CodeBlock code={`builder.Services.AutoRegisterRequestHandlers();

// Override a specific handler with a custom implementation
builder.Services.AddRequestHandler<GetUserQuery, User, CachedGetUserQueryHandler>();`} />
        </div>
    );
};

export default AutoRegistration;
