import React from 'react';
import { Link } from 'react-router-dom';
import CodeBlock from '../../components/CodeBlock';
import H2 from '../../components/DocHeading';
import Callout from '../../components/Callout';

const AutoRegistration = () => {
    const basicUsageCode = `using MediatRR.ServiceGenerator;

var builder = WebApplication.CreateBuilder(args);

// Auto-register all request handlers in this project
builder.Services.AutoRegisterRequestHandlers();

// Auto-register all stream handlers in this project
builder.Services.AutoRegisterStreamHandlers();

var app = builder.Build();`;

    const handlerCode = `// Just implement IRequestHandler - no manual registration needed!
namespace MyApp;

public class GetUserQuery : IRequest<User>
{
    public string UserId { get; set; }
}

public class GetUserQueryHandler : IRequestHandler<GetUserQuery, User>
{
    public Task<User> Handle(GetUserQuery request, CancellationToken cancellationToken)
    {
        // Handler implementation
        return Task.FromResult(new User { Id = request.UserId });
    }
}`;

    const generatedCode = `// <auto-generated/>
namespace MediatRR.ServiceGenerator
{
    internal static class SourceGeneratorInjectDependencies
    {
        internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AutoRegisterRequestHandlers(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<global::MediatRR.Contract.Messaging.IRequestHandler<global::MyApp.GetUserQuery, global::MyApp.User>, global::MyApp.GetUserQueryHandler>(services);
            return services;
        }

        internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AutoRegisterStreamHandlers(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            return services;
        }
    }
}`;

    const multiProjectCode = `// MyApp.Application (class library with the handlers)
using MediatRR.ServiceGenerator;
using Microsoft.Extensions.DependencyInjection;

public static class ApplicationServiceCollectionExtensions
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
        => services.AutoRegisterRequestHandlers().AutoRegisterStreamHandlers();
}

// MyApp.Web (the host)
builder.Services.AddMediatRR(cfg => { }, deadLetters);
builder.Services.AddApplication();`;

    const overrideCode = `builder.Services.AutoRegisterRequestHandlers();

// Override a specific handler with a custom implementation
builder.Services.AddRequestHandler<GetUserQuery, User, CachedGetUserQueryHandler>();`;

    return (
        <div>
            <h1>Auto-Registration</h1>
            <p className="doc-lead">
                MediatRR includes a source generator that discovers and registers all request and stream
                handlers in a project. This eliminates manual registration and the assembly scanning other
                libraries do at start-up.
            </p>

            <H2>How It Works</H2>
            <p>
                The source generator scans your code at compile time, finds the classes that
                implement <code>IRequestHandler&lt;TRequest, TResponse&gt;</code> or{' '}
                <code>IStreamRequestHandler&lt;TRequest, TResponse&gt;</code>, and generates registration code
                automatically. It registers:
            </p>
            <ul>
                <li>Non-abstract, non-generic classes and records</li>
                <li>Every handler interface a class implements, so one class can handle several request types</li>
                <li>Nested classes, as long as the class and every class it is nested in are public or internal</li>
            </ul>
            <p>
                Notification handlers are not auto-registered; register them
                with <Link to="/docs/notifications">AddNotificationHandler</Link>, which also carries their
                retry policy.
            </p>

            <H2>Usage</H2>
            <p>
                Call <code>AutoRegisterRequestHandlers()</code> or <code>AutoRegisterStreamHandlers()</code> on your service collection:
            </p>
            <CodeBlock code={basicUsageCode} />

            <H2>Creating Handlers</H2>
            <p>
                Just implement <code>IRequestHandler</code> - no attributes or manual registration required:
            </p>
            <CodeBlock code={handlerCode} />

            <H2>Generated Code</H2>
            <p>
                Behind the scenes, the source generator creates extension methods that register all handlers.
                Both methods always exist, even when there is nothing to register:
            </p>
            <CodeBlock code={generatedCode} />

            <H2>Handlers in Other Projects</H2>
            <p>
                The generator runs separately in every project that references the <code>MediatRR</code>{' '}
                package, and the methods it generates are <code>internal</code> to that project and cover only
                the handlers declared there. Analyzers do not flow through project references, so a class
                library that contains handlers needs its own package reference and should expose its
                registrations itself:
            </p>
            <CodeBlock code={multiProjectCode} />

            <Callout variant="warning" title="One generated class per project">
                <p>
                    Calling <code>AutoRegisterRequestHandlers()</code> in the host registers the host's handlers
                    only. If your handlers live in a class library and nothing calls that library's generated
                    methods, <code>Send</code> throws <code>InvalidOperationException</code> for a missing handler
                    at runtime.
                </p>
            </Callout>

            <H2>Requirements</H2>
            <ul>
                <li>The generator ships inside the MediatRR package; there is nothing else to install</li>
                <li>It runs on the .NET SDK 6.0.400 or later, or Visual Studio 2022 17.3 or later</li>
                <li>
                    The generated code uses only C# 7.3 syntax and fully qualified names, so it also compiles
                    in projects on older language versions, such as <code>netstandard2.0</code> and .NET
                    Framework libraries
                </li>
            </ul>

            <H2>Benefits</H2>
            <ul>
                <li><strong>Zero boilerplate</strong>: no need to manually register each handler</li>
                <li><strong>Compile-time safety</strong>: registration happens at compile time, not runtime</li>
                <li><strong>No reflection</strong>: no assembly scanning at startup, so applications start faster</li>
                <li><strong>Automatic discovery</strong>: new handlers are registered as soon as you add them</li>
                <li><strong>Type safe</strong>: all registrations are strongly typed</li>
            </ul>

            <H2>Namespace</H2>
            <p>
                The auto-registration feature is available in the <code>MediatRR.ServiceGenerator</code> namespace:
            </p>
            <CodeBlock code="using MediatRR.ServiceGenerator;" language="csharp" />

            <H2>Combining with Manual Registration</H2>
            <p>
                You can still manually register handlers if needed. A manual registration made after the
                auto-registration call overrides the auto-registered handler:
            </p>
            <CodeBlock code={overrideCode} />
        </div>
    );
};

export default AutoRegistration;
